name: 'Reusable CI Workflow    Node Npm'
on:
 workflow_call:
    inputs:
      application:
        required: true
        type: string
      repository_name:
        required: true
        type: string
      nodeVersion:
        required: true
        type: string
      WorkingDirectory:
        required: true
        type: string

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.sha }}
  cancel-in-progress: false
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ inputs.nodeVersion }}

      - name: Install dependencies
        run: npm install
        working-directory: ${{ inputs.WorkingDirectory }}

      - name: Run tests
        run: npm test
        working-directory: ${{ inputs.WorkingDirectory }}

      - name: Build application
        run: npm run build
        working-directory: ${{ inputs.WorkingDirectory }}

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v6 # Official unified action
        env:
          SONAR_TOKEN: e2d82d80bed1e2f3a9d3ad9104e39404f6796e19
      
